#!/usr/bin/env python3
"""
Set up (or remove) a local daily scheduled task that keeps a token-heatmap.svg
fresh automatically: collect usage -> render SVG -> git commit -> git push.

This exists because the source data lives only on this machine - no cloud
runner can reach it, so "auto-update" has to mean a local scheduler. It uses
Windows Task Scheduler (schtasks) on Windows and cron on macOS/Linux.

This registers something that pushes to a git remote unattended, on a
schedule, forever, until removed. Run this only after the user has explicitly
asked for automatic daily updates and confirmed the target repo, branch, and
time - never as a default part of installing or running the skill.
"""
import argparse
import datetime
import os
import platform
import subprocess
import sys

SKILL_DIR = os.path.dirname(os.path.abspath(__file__))
TASK_NAME = "TokenHeatMapDailyUpdate"


def run(cmd, **kwargs):
    return subprocess.run(cmd, check=True, **kwargs)


def git(repo_dir, *args, check=True):
    return subprocess.run(["git", "-C", repo_dir, *args], check=check,
                           capture_output=True, text=True)


def validate_repo(repo_dir):
    if not os.path.isdir(os.path.join(repo_dir, ".git")):
        sys.exit(f"error: {repo_dir} is not a git repository (no .git dir).")
    remotes = git(repo_dir, "remote").stdout.strip()
    if not remotes:
        sys.exit(f"error: {repo_dir} has no git remote configured - nothing to push to.")


def write_wrapper_unix(repo_dir, svg_name, html_name, data_name, branch):
    path = os.path.join(repo_dir, ".token-heatmap-autoupdate.sh")
    content = f'''#!/bin/sh
# Auto-generated by setup_autoupdate.py - safe to delete along with its cron entry.
set -e
cd "{repo_dir}"
python3 "{SKILL_DIR}/collect_usage.py" --out "{data_name}"
python3 "{SKILL_DIR}/render_svg.py" --data "{data_name}" --out "{svg_name}"
python3 "{SKILL_DIR}/render_html.py" --data "{data_name}" --out "{html_name}"
if [ -n "$(git status --porcelain -- "{svg_name}" "{html_name}" "{data_name}")" ]; then
  git add "{svg_name}" "{html_name}" "{data_name}"
  git commit -m "chore: update token heatmap"
  git push origin "{branch}"
fi
'''
    with open(path, "w", newline="\n") as fh:
        fh.write(content)
    os.chmod(path, 0o755)
    return path


def write_wrapper_windows(repo_dir, svg_name, html_name, data_name, branch):
    path = os.path.join(repo_dir, "token-heatmap-autoupdate.bat")
    content = f'''@echo off
REM Auto-generated by setup_autoupdate.py - safe to delete along with its scheduled task.
cd /d "{repo_dir}"
python "{SKILL_DIR}\\collect_usage.py" --out "{data_name}" || exit /b 1
python "{SKILL_DIR}\\render_svg.py" --data "{data_name}" --out "{svg_name}" || exit /b 1
python "{SKILL_DIR}\\render_html.py" --data "{data_name}" --out "{html_name}" || exit /b 1
git status --porcelain -- "{svg_name}" "{html_name}" "{data_name}" > nul
for /f %%i in ('git status --porcelain -- "{svg_name}" "{html_name}" "{data_name}"') do (
  git add "{svg_name}" "{html_name}" "{data_name}"
  git commit -m "chore: update token heatmap"
  git push origin {branch}
  goto :done
)
:done
'''
    with open(path, "w", newline="\r\n") as fh:
        fh.write(content)
    return path


def install_cron(wrapper_path, time_hhmm, log_path):
    hh, mm = time_hhmm.split(":")
    line = f'{int(mm)} {int(hh)} * * * /bin/sh "{wrapper_path}" >> "{log_path}" 2>&1'
    existing = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    current = existing.stdout if existing.returncode == 0 else ""
    lines = [l for l in current.splitlines() if wrapper_path not in l]
    lines.append(f"# {TASK_NAME}")
    lines.append(line)
    new_crontab = "\n".join(lines) + "\n"
    subprocess.run(["crontab", "-"], input=new_crontab, text=True, check=True)
    return line


def uninstall_cron(wrapper_path):
    existing = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    if existing.returncode != 0:
        return
    lines = existing.stdout.splitlines()
    kept = [l for l in lines if wrapper_path not in l and TASK_NAME not in l]
    subprocess.run(["crontab", "-"], input="\n".join(kept) + "\n", text=True, check=True)


def install_schtasks(wrapper_path, time_hhmm):
    run([
        "schtasks", "/Create", "/SC", "DAILY", "/TN", TASK_NAME,
        "/TR", f'"{wrapper_path}"', "/ST", time_hhmm, "/F",
    ])


def uninstall_schtasks():
    subprocess.run(["schtasks", "/Delete", "/TN", TASK_NAME, "/F"], check=False)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-dir", default=os.getcwd(), help="Repo containing the heatmap (default: cwd)")
    parser.add_argument("--time", default="06:00", help="Local time to run daily, HH:MM 24h (default: %(default)s)")
    parser.add_argument("--branch", default=None, help="Branch to push to (default: current branch)")
    parser.add_argument("--svg-name", default="token-heatmap.svg")
    parser.add_argument("--html-name", default="token-heatmap.html")
    parser.add_argument("--data-name", default="token-heatmap-data.json")
    parser.add_argument("--uninstall", action="store_true", help="Remove the scheduled task instead of creating it")
    args = parser.parse_args()

    repo_dir = os.path.abspath(args.repo_dir)
    validate_repo(repo_dir)
    branch = args.branch or git(repo_dir, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()

    system = platform.system()

    if system == "Windows":
        wrapper_path = os.path.join(repo_dir, "token-heatmap-autoupdate.bat")
        if args.uninstall:
            uninstall_schtasks()
            if os.path.exists(wrapper_path):
                os.remove(wrapper_path)
            print(f"Removed scheduled task '{TASK_NAME}' and {wrapper_path}")
            return
        wrapper_path = write_wrapper_windows(repo_dir, args.svg_name, args.html_name, args.data_name, branch)
        install_schtasks(wrapper_path, args.time)
        print(f"Installed Windows scheduled task '{TASK_NAME}' running daily at {args.time}.")
        print(f"Wrapper script: {wrapper_path}")
        print("View/remove it any time via Task Scheduler, or re-run this script with --uninstall.")
    else:
        wrapper_path = os.path.join(repo_dir, ".token-heatmap-autoupdate.sh")
        log_path = os.path.join(repo_dir, ".token-heatmap-autoupdate.log")
        if args.uninstall:
            uninstall_cron(wrapper_path)
            if os.path.exists(wrapper_path):
                os.remove(wrapper_path)
            print(f"Removed cron entry and {wrapper_path}")
            return
        wrapper_path = write_wrapper_unix(repo_dir, args.svg_name, args.html_name, args.data_name, branch)
        cron_line = install_cron(wrapper_path, args.time, log_path)
        print(f"Installed cron entry running daily at {args.time}: {cron_line}")
        print(f"Wrapper script: {wrapper_path}")
        print(f"Logs: {log_path}")
        print("View with `crontab -l`, or re-run this script with --uninstall.")

    print()
    print("This pushes to your git remote unattended on a schedule. Make sure")
    print("`git push` already works non-interactively from this machine for this")
    print(f"repo (cached credentials / SSH agent) - test with: git -C {repo_dir} push")


if __name__ == "__main__":
    main()
